spring.application.name=geographical
spring.datasource.url=jdbc:postgresql://localhost:5432/geodb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.security.user.name=admin
spring.security.user.password=admin123